export enum ClientStatus {
  PENDING_CREATION = 'PENDING_CREATION',
  CREATED = 'CREATED',
  SUSPENDED = 'SUSPENDED',
  IN_ERROR = 'IN_ERROR',
  PENDING_DELETION = 'PENDING_DELETION',
  DELETED = 'DELETED'
}
